version: 'Spec'
volumes:
  postgres-data:

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pj_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
